Update pr-kicad-diff.yaml

diff --git a/.github/workflows/pr-kicad-diff.yaml b/.github/workflows/pr-kicad-diff.yaml
--- a/.github/workflows/pr-kicad-diff.yaml
+++ b/.github/workflows/pr-kicad-diff.yaml
@@ -18,6 +18,7 @@ on:
 jobs:
   kiri-diff:
     runs-on: ubuntu-latest
+    timeout-minutes: 10
     steps:
     - uses: actions/checkout@v4
       with:
@@ -34,11 +35,16 @@ jobs:
       run: |
         mkdir -p ./diff
         echo "<html><body>test</body></html>" > ./diff/index.html
-        
+
+    - name: Check KiCad project exists
+      run: |
+        echo "Checking project file path..."
+        ls -l /github/workspace/projekt1/new.kicad_pro || echo "File not found!"
+      
     - name: Kiri
       uses: hacker-fab/kiri-github-action@v2.0.5
       with:
-        project-file: projekt1/new.kicad_pcb
+        project-file: /github/workspace/projekt1/new.kicad_pro
         output-dir: ./diff/
         kiri-debug: true
         extra-args: --exclude "/etc" --exclude "/dev" --exclude "/boot" --exclude "/home" --exclude "/mnt" --exclude "/lost+found"
